import {
  MAX_CONVERSATION_TEXT_BYTES,
  MAX_PLANNER_RESULT_ENVELOPE_BYTES,
} from '../../resource_limits.ts';

export const MAX_REPLAY_MESSAGE_TEXT_BYTES = MAX_CONVERSATION_TEXT_BYTES;
export const MAX_REPLAY_PLANNER_RESULT_BYTES = MAX_PLANNER_RESULT_ENVELOPE_BYTES;
